# Generated by Django 3.2.6 on 2021-08-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210824_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city_birth',
            new_name='city_birthday',
        ),
    ]
