# Generated by Django 3.2.6 on 2021-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_city_birth_student_city_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10, verbose_name='gender'),
        ),
    ]
